### ISSUE TITLE
Optimistic concurrency conflicts detection

### ISSUE THREAD

**Issue by pawelpawlow** [yevhen/Streamstone#12]
I'm not sure how concurrency conflicts (head version) are detected. Say I load all the events from a stream twice (to two instances of an aggregate, say A and B) and then try to save  eventA from A and eventB from B. I  expect concurrency conflict exception for the latter, but both events are saved.
Can you show concurrency conflict detection scenario?

What's the idea behind duplicate event detection (event id)? My domain events has the id of the aggregate.

**Comment by pawelpawlow** [comment]
Should I check the Stream.Version returned by Stream.Open()?

**Comment by yevhen** [comment]
Hi Pawel,

> I expect concurrency conflict exception for the latter, but both events are saved.

That's not possible. Could be confirmed by [this](https://github.com/yevhen/Streamstone/blob/master/Source/Streamstone.Tests/Scenarios/Writing_to_stream.cs#L32) passing test. Except that you're doing something wrong. I suspect that you open stream on each write.

You should open/create stream when loading/creating aggregate and hold returned `Stream` header.  Then you need to use (and update) it for subsequent operations (writes). It encapsulates `Etag` and `Version` and that's how concurrency is detected.

See [this](https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S04_Write_to_stream.cs) and [this](https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S08_Concurrency_conflicts.cs) scenario for example. Also, check out more comprehensive sample of [event-sourced actor](https://github.com/yevhen/Orleankka/blob/master/Source/Example.EventSourcing.Persistence.Streamstone/Infrastructure.cs#L46) (which is kinda like Aggregate, just sitting always in memory) which you can use as a basis.

**Comment by yevhen** [comment]
> What's the idea behind duplicate event detection (event id)? My domain events has the id of the aggregate.

Event id is a unique id of the event itself. Primary use is for implementing idempotence. 

Suppose that you're processing commands off of the durable queue. Now you're dealing with 2 separate transactional resources - queue and event-store. Having distributed transaction between them is either impossible (common case in a cloud environment) or undesirable (for performance reasons), so that occasional crash between the moment you persisted events to ES and the moment you've ACKed the command to remove it from queue, may lead to command being processed twice (or more). You can imagine how bad is that for certain domains (accounting, banking, etc).

The fix is simple. You may derive event id from command id and then rely on ES giving you back (duplicate event id) exception, so you can simply remove command from queue and proceed, since the command was already processed (and now you know that your system/transaction was crashed just before ACKing the command).

That's an advanced use-case. Nevertheless, having support for that out-of-the-box is really nice :grimacing:

**Comment by yevhen** [comment]
@pawelpawlow Does it help?

**Comment by pawelpawlow** [comment]
Yes, thank you for the clarification and the Orleans example.
I'm want to use Streamstone to implement event sourced repository for my CQRS DDD app. My Aggregates have int Version property that I would like to use for concurrency conflict detection.
If I check stream's version after open(), will this be enough to detect possible concurrency conflict?

**Comment by yevhen** [comment]
Nope. You should hold returned Stream header and use it for subsequent
operations and replacing it after each write.

2015-07-03 12:54 GMT+03:00 PAWEŁ PAWŁOW notifications@github.com:

**Comment by pawelpawlow** [comment]
Ok, I think we can close this one.
It would be very helpful If you provide a Streamstone version of the [Greg Young's Simple CQRS](https://github.com/gregoryyoung/m-r) :) - or at least some guide lines.

**Comment by pawelpawlow** [comment]
Regarding the event id - yes, I'm processing commands, but each command can produce multiple events that I want to store. If I introduce unique command id and combine it with say the index of the event it has produced, then this may serve as unique event id, I think?

**Comment by yevhen** [comment]
Yes, That what everyone do.

2015-07-03 13:49 GMT+03:00 PAWEŁ PAWŁOW notifications@github.com:

**Comment by yevhen** [comment]
I'm working on that :)

2015-07-03 13:48 GMT+03:00 PAWEŁ PAWŁOW notifications@github.com:
