### ISSUE TITLE
Multitenant concurrency?

### ISSUE THREAD

**Issue by turowicz** [yevhen/Streamstone#13]
Will the following example throw concurrency exceptions for multitenant operations too?

https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S08_Concurrency_conflicts.cs

**Comment by yevhen** [comment]
I'm not sure I'm following you on this. What do you mean by multi-tenant?

There various ways how you can model multi-tenant apps with Streamstone.
1. One physical partition for tenant, virtual partitions (inside that physical partition) for each stream. That way you _can_ have transaction around writing events into a stream and writing some entities at partition level. That's how inline synchronous fully consistent projections/snapshots could be implemented (in theory), where partition level entities could be an aggregation rows (such as counters) and concurrency for those rows should be managed by using normal WATS means, such as `Etag`. Ie, you need to read partition-level aggregation rows (table entities) before including them in transaction when writing events to stream.
2. One physical partition for stream. Then you can model multi-tenancy by implementing `stream directory` so that you know which tenant has which streams and where. 

In both cases, concurrency will always be handled for any stream-level operation. In 1-st case, concurrency for partition-level entities could be controlled by developer, using regular semantics of table operations (Insert, InsertOrReplace, Replace).

**Comment by yevhen** [comment]
Checkout  `Include.XXX` class and sample [here](https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S06_Include_additional_entities.cs) for how you can include additional entities when writing events (within same transaction).

**Comment by yevhen** [comment]
@turowicz Can I close this?

**Comment by turowicz** [comment]
thanks!
