### ISSUE TITLE
Support for Subsribing/Consuming events

### ISSUE THREAD

**Issue by gabikliot** [yevhen/Streamstone#15]
I have a question if you plan to support (or maybe already support) an consuming events from StreamStone like a queue? So that I can "subscribe" logically to it and will be pushed/notified when new event is appended?
Something like the new DynamoDB streams: http://www.allthingsdistributed.com/2015/07/dynamodb-streams.html

**EDIT:** Is that [Reading from a stream](https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S05_Read_from_stream.cs)? How do you read? Do you periodically pull?

Also, what about the order? Who orders on ingestion - application provides sequence number or the library? Is read guaranteed to be ordered? 

What about multiple (potentially distributed producers?)

I am asking all this not to punch holes. I am actually very excited about it and trying to learn what it does and how.

**Comment by yevhen** [comment]
Hi @gabikliot !

Cool to see you here. Glad you liked the project :smile:
Now, regarding your questions:

> if you plan to support (or maybe already support) an consuming events from StreamStone like a queue

yes. Event stream is intrinsically a queue. You can consume event stream in that way.

> So that I can "subscribe" logically to it and will be pushed/notified when new event is appended?

Streamstone is a serverless, stateless, in-process library. It's just a thin layer on top of WATS that fully implements event-store semantics (using WATS tables/partitions). So there is nothing that you can subscribe to for receiving push-based notifications. I was thinking about implementing something like that with the help of Orleans but that will probably be a different project/product.

> EDIT: Is that Reading from a stream? How do you read? Do you periodically pull?

It depends on app/logic. Usual pattern for stateless applications is to read (replay) stream on every request, optionally using snapshots to speed up replaying, apply logic from incoming request (execute command) and then save newly produced events. That's how regular event-sourced app ala Greg Young usually look [like](https://github.com/gregoryyoung/m-r).

For stateful apps, we keep current state in memory and we skip reading the stream on every request. We only flush changes to storage (after applying incoming request to in-memory state). There is no need to periodically pull changes since there is always a single writer (to a stream). An example of using Streamstone in stateful app is [here](https://github.com/yevhen/Orleankka/tree/master/Source/Example.EventSourcing.Persistence.Streamstone).

However, that's only true for Command Handlers but not for Projections. Projections usually poll stream for changes, storing last seen sequence id by themselves and asking for changes starting from the last seen id (quite similar to Orleans' streams). As an optimization push can be used instead, so that Command Handlers will publish events (after storage ACKed the write) directly to projections.

> Also, what about the order? Who orders on ingestion - application provides sequence number or the library? Is read guaranteed to be ordered? 

Yes, the order is guaranteed. You can read stream starting at any revision. Stream has monotonically increasing sequence id (version) with no gaps.

> What about multiple (potentially distributed producers?)

No problem. However, according to a semantics of event-sourcing the ordering and hence versioning is very strict. Concurrency conflict detection is based on Etags. In case of conflicts, stream need to be re-read (replayed) to get latest Etag and then command could be retried. That's how all event-sourced apps are usually implemented (expected version of stream is supplied by writer).

> I am asking all this not to punch holes. I am actually very excited about it and trying to learn what it does and how.

Cool! Feel free to ask more questions. Also, you're welcome to Gitter chat! :smile:

**Comment by gabikliot** [comment]
Thanks for your answers @yevhen !
So lets see if I got it right: 
1) For Commands single consumer only . 
2) For Projections may have multiple consumers. 
3) In both cases there is currently no push based delivery mechanism.
4) Pull is done by reading starting from the  sequence id  that is provided by the reader (client).
5) Order on ingestion (write) is provided by client specifying sequence id - that is, producer explicitly orders the data by himself.  
6) If there happen to be multiple producers, they need to agree on order between themselves and provide distinct sequence id (if both want to ensure data is stored).

Is it all correct?

What I meant by "queue" is [distributed log](https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying). That is, a system where multiple producers produce into a log and their data is appended, in the order it arrives to the log. They do NOT have to provide sequence ids themselves. Ordering the logs (in a scalable and reliable distributed manner) is the "heavy lifting" that the logs implementation is doing. On the consumer side they can either consume starting from a given sequence  if (offset) in the log or subscribe to receive all latest. But indeed the 2nd part - push based from head, is actually not what make it a log or queue. The most important is ordering upon the append.

**Comment by yevhen** [comment]
Correct!

> 5) Order on ingestion (write) is provided by client specifying sequence id - that is, producer explicitly orders the data by himself.

Yes, but transitively. Since consumers give back etags, which coud be equated to giving back last version seen. It goes like this:

_Consumer_: last time when I've read this stream it was of version 8 (sequence id) and you gave me this etag. Now, I want to append 10 events and I give you etag I've got from you back then. I do expect that stream is still untouched since I last read it.
_Producer_: sure, go ahead. Oops, someone written new events to this stream behind your back. So you need to pull the changes (and updated etag), re-apply your logic (which has produced 10 events before) since it now may be invalid due to the changes that happened to a stream.

Good example is invoice approval. Imagine, that 2 users have both opened an invoice form. One is a manager and other one is employee. The stream behind an invoice is of version 1 - there is only a single event InvoiceCreated. An invoice has a total of $500 which is within a possible limit of $1K. 

So the manager is happy to approve it an pushes the Approve button, while simultaneously an employee changes the total to $2K and he is first to commit. The stream is now at version 2. There 2 events - InvoiceCreated, InvoiceTotalChanged.

If we do allow InvoiceApproved to be commited just on top - we blew everything. Actually, it's true an other way around as well. We can't just allow InvoiceTotalChanged after InvoiceCreated. That is the reason why we can't just increment sequence number and need to repeat the logic if stream changed since last read.

> The most important is ordering upon the append.

I've stated explicitly on title page that "Streamstone ... is targeted at building scalable event-sourced applications". As per event-sourcing theory it's not only about incrementing sequence number per se. It's all about having a single writer, since the stream itself is always thought of as a single value (ie, current state, a left fold of events) and we do always use some form (optimistic/pessimistic) of locking around it.

So, no. Streamstone is not a distributed log, like Kafka. It is an Event Store similar to this https://geteventstore.com/

**Comment by yevhen** [comment]
BTW, Greg's event store has an ability to ignore stream version and just append events to an end, effectively making it a distributed log. But that's only possible since his Event Store is a fully-fledged server application while SS is serverless library.

**Comment by gabikliot** [comment]
Got it!

So according to event-sourcing theory, event-sourcing by definition is for single writer (as you wrote above)? But you just gave an example with invoice of 2 writers?

**Comment by yevhen** [comment]
Sorry, mistype on my part. It should be "according to DDD theory". Aggregates and all that.

In the example I gave you there is a singe writer at a time. It's single writer since other writers do care that the value hasn't changed since the time they have read it. Optimistic locking is usually employed to implement this behavior.

Azure queues and Orleans streams have different semantics. They allow multiple writers. Where writers don't care about other writers.

**Comment by gabikliot** [comment]
Sorry, but what you just wrote really confuses me: "It's single writer since other writers do care that the value hasn't changed since the time they have read it."

If there are other writers, it cannot be a single writer, ... by definition of what single means. Especially if other writers care. 

Are you saying  it is a "singe writer at a time", so in any  given time period (**any** time period) there should be only one writer. If somehow by mistake there happen to be 2 writers writing simultaneously without knowing each other, the system prevents that from  happening. But if they are aware of each other and serialize their writes via sequence number/etags, than they are both allowed to write. I would call that pattern **"no concurrent writers"**, not a **"single writer"**.

**Comment by yevhen** [comment]
Well, let call it like you're suggesting. The point is: writing to a stream concurrently is not possible.

**Comment by gabikliot** [comment]
Got it! Makes sense. Thanks for clarifying.
