### ISSUE TITLE
Example for projections (read model)?

### ISSUE THREAD

**Issue by emragins** [yevhen/Streamstone#26]
I followed the "simplest thing possible" example for getting a write-side in place (with some modifications, of course), and I really like the direction my application is headed in.  It was quick an easy with basically no issues.

I'm struggling with developing a sufficiently robust read-side.  Doing everything real-time, while easy to implement and understand, just begs for problems the second something doesn't work perfectly (because that NEVER happens in software). 

I have a couple ideas of how I might be able to shimmy something in place, but since I know this is not by any means a unique situation I'd rather follow an established pattern.

Thanks for everything!  :)

**Comment by yevhen** [comment]
You're welcome!

Ye, inline projections in SS are suitable only for simple cases. For anything more involved it's indeed better to follow the patterns established by classic CQRS\ES literature.

Nevertheless, I did some small demo using Greg Young's classic example. See here https://github.com/yevhen/Streamstone.m-r/tree/inline_projections

Thanks for kind words. Be my guest on Streamstones' gitter chatroom.

**Comment by alexeyzimarev** [comment]
The issue there is as usual that writing events and publishing them to projections are two separate operations that involve independent infrastructural component. And since they do not run in a transaction, one could fails without the other knowing about it. For example, in your sample events are being published to projections and then written to the event store. It means that projections could update the read model without events being actually committed. GES solves this problem using subscriptions. Everyone who I talked to about event sourcing point this as a challenge. One exception there and you get inconsistent models with hard recovery path.
