### ISSUE TITLE
Writing large number of events to the stream

### ISSUE THREAD

**Issue by jkonecki** [yevhen/Streamstone#3]
Currently Stream API throws AgrumentOutOfRange exception when trying to write more than 49 events to a stream.

The limit comes from the technical, implementation detail of WATS batch operations limits and not IMHO from the domain concept of the stream itself. I believe the API client shouldn't worry about such details and Stream API should handle writing events in multiple batches. Otherwise every client will have to implement batching logic over API.

I attach an updated unit test that describes my desired behaviour.

**Comment by yevhen** [comment]
I agree, that automatic batching is nice to have feature. Thus, it is something that could be easily built on top of current api. I would prefer it to be implemented this way (and adhering to SRP), rather than running with the scissors ;)

If you think about it, the api with automatic batching will be quite different from the current one. For example, imagine that you're writing 1000 events and on second page it fails. You'll need to communicate back, that only first 49 events were written successfully. `StreamWriteResult` api won't cut, and more extended api with different semantics is needed (say, `BatchStreamWriteResult`).

I can create new issue for "automatic batching api" to discuss possible designs or we can do it within this one. What do you think?

**Comment by jkonecki** [comment]
Let's do it within this issue.
I'm happy with introducing a new API method that returns a collection of results for each page.
I was thinking about an automatic _rollback_ by deleting already written pages but that may fail as well.

**Comment by yevhen** [comment]
I want all stream operations to stay ACID. So no "rollbacks", please :)

**Comment by jkonecki** [comment]
No worries. We don't want to start doing rollbacks  of rollbacks... ;-)
