### ISSUE TITLE
Support for drop in replacement using DocumentDb/CosmosDB

### ISSUE THREAD

**Issue by andrejohansson** [yevhen/Streamstone#35]
Document DB have now been renamed to Cosmos DB and according to the documentation it should be able to act as a drop in replacement for Azure table storage. It sounds like if this is true, it should be a trivial matter to add suppport for it?

You need to use the new Azure Preview SDK in order to get the features to connect to Cosmos but the api should be compatible with the existing  storage Api. See

References
- [Azure Cosmos DB: Build a .NET application using the Table API](https://docs.microsoft.com/en-us/azure/cosmos-db/create-table-dotnet)
- [Windows Azure Storage Premium Table 0.1.0-preview nuget package](https://www.nuget.org/packages/WindowsAzure.Storage-PremiumTable/0.1.0-preview)

**Comment by yevhen** [comment]
I think we first need to finish the work started on porting to .NET Core and then it will be easier to add support for latest AzureSDK (CosmosDb).

**Comment by andrejohansson** [comment]
@yevhen I see that the nuget package now builds for netstandard, doeast it mean AzureSDK can be added now? :-)

**Comment by yevhen** [comment]
@andrejohansson I think so. Do you have vision on how best to proceed with that? We can discuss the approach and I'll surely accept PR? ))

**Comment by andrejohansson** [comment]
For a brute force approach, I just wanted to try to replace it and se if something starts at all.

I´ve tested the following: 

- Clone your project
- Replace the Storage nuget package with the PremiumTable on. Building goes fine.
- Created a Cosmos DB with the table storage model
- Referenced the project from our main solution
- Tried to run, but I get invalid calls for pretty much all api calls (such as "table.Exists"). I will investigate this further today.

As for vision, the main reason for me for preferring to use Cosmos is that I'm hoping to use more advanced features (better query language, triggers etc). But I'm unsure of what will be available. Have to try atleast!

**Comment by yevhen** [comment]
I don't want to switch (*replace*) WindowsAzure.Storage dependency to CosmosDb. The vast majority of SS users use the former. I'd like them to co-exist. I think it would be better to create another package like Streamstone.CosmosDb for that. 

I see it like this:
1. Create second set of project files which do reference CosmosDb. So in every folder there will be XXX.CosmosDb.proj (Example.CosmosDb, Streamstone.CosmosDb and Streamstone..CosmosDb.Tests). Change output dir to bin\CosmosDb to prevent binary conflicts
2. Create second nuspec with dependency on CosmosDb
3. Extend build script so that it creates Streamstone.CosmosDb package. 

But sure, first to figure out why it doesn't work ;)

**Comment by yevhen** [comment]
I believe we can close this one. Check out this announcement https://azure.microsoft.com/blog/announcing-the-general-availability-of-azure-cosmosdb-table-api/

It means to take advantage of CosmosDb only connection string need to be changed. No need to switch SDK

**Comment by andrejohansson** [comment]
Nice! Hoping to get time to try this out soon.
