### ISSUE TITLE
Implementing read models

### ISSUE THREAD

**Issue by fschmied** [yevhen/Streamstone#36]
@yevhen Could you elaborate on how to implement read models with Streamstone? Is there a subscription mechanism (like with Greg Young's EventStore) or a complete event sequence with a global ordering (like with NEventStore)? The example links about "creating projections" and "querying events" are broken, and https://github.com/yevhen/Streamstone/issues/26#issuecomment-230809565 looks like there is no read model mechanism at all?

**Comment by yevhen** [comment]
SS allows you to easily create projections for a single stream - you can use stream version which is sequential number. Creating projections across streams was out of scope since SS is just a simple in-process library and for this a global sequence / all stream (like in GY EventStore) is required. Otherwise, if the cardinality of your projection is low you can monitor multiple streams and build projection out of combined sequencing.

**Comment by fschmied** [comment]
Okay, thanks for the answer.

----- Ursprüngliche Nachricht -----
Von: "Yevhen Bobrov" <notifications@github.com>
Gesendet: ‎16.‎06.‎2017 19:22
An: "yevhen/Streamstone" <Streamstone@noreply.github.com>
Cc: "Fabian Schmied" <fabian.schmied@gmail.com>; "Author" <author@noreply.github.com>
Betreff: Re: [yevhen/Streamstone] Implementing read models (#36)

SS allows you to easily create projections for a single stream - you can use stream version which is sequential number. Creating projections across streams was out of scope since SS is just a simple in-process library and for this a global sequence / all stream (like in GY EventStore) is required. Otherwise, if the cardinality of your projection is low you can monitor multiple streams and build projection out of combined sequencing.
