### ISSUE TITLE
Does the package target .NET Core or .NET Framework 4.6.1 ?

### ISSUE THREAD

**Issue by MNF** [yevhen/Streamstone#39]
In the readme.md there is a phrase that we need .NET Core SDK 2.0 **and** .NET Framework 4.6.1 .
Does it mean, that the project  targets full .net framework and can’t be run on other platforms like Linux?

**Comment by yevhen** [comment]
Nope. The package itself targets .NET Standard 2.0. Which means you can use it either on full .NET framework (Win) or on .Net Core (Win/Linux). The example app and unit tests target .NET Core (since entry points need to specify particular version of CLR as per .NET requirements) which means you can run them both on Windows and Linux, but you will need to have .NET Core installation.

**Comment by yevhen** [comment]
I've removed confusing statement from README (https://github.com/yevhen/Streamstone/commit/daf61ad5e58453b0ee4964d4335690fbc2709c68)
