### ISSUE TITLE
Possible for read StreamSlice header to have a lower version than number of retrieved events?

### ISSUE THREAD

**Issue by Davidsv** [yevhen/Streamstone#49]
Hi, imagine this scenario:
- Stream already has 5 events.
- Start reading a streamslice, starting from 1. Azure will start to read current header which has version 5 and search for any events from 1. Azure reads the header entity but is still scanning through the rows...
- From elsewhere a successful batch write on the same stream is done with 30 events including header, header will now have version 5+30 = 35
- Reading is still ongoing, and it also got the new events. Resultant StreamSlice.Stream.Version is now 5 but StreamSlice.Events array has 35 items.

This is difficult to test due to small time window where this could happen which is why I'm asking if it's even possible. I think batch writes are atomic, but are reads (within one GET)?

```
StreamSlice<DynamicTableEntity> read = await Stream.ReadAsync<DynamicTableEntity>(partition, 1);
Int32? lastEventsVersion = read.Events.LastOrDefault()?.Properties["Version"].Int32Value;
if (read.Stream.Version < lastEventsVersion)
{
    Console.WriteLine("inconsistent");
}
```

**Comment by yevhen** [comment]
Hi,

Ye, I think it's totally possible. 

Nevertheless, I never intended the returned stream header to be consistent with the number of events in the slice. The stream header is returned along with the slice only for informational purposes, like what is the current state of the stream at the time of reading a slice. 

That's why `ReadAsync()` api [method](https://github.com/yevhen/Streamstone/blob/master/Source/Streamstone/Stream.Api.cs#L330) doesn't require you to pass the header and only uses stream version. So, when reading use the version of the last event in the current slice to read the next slice.

**Comment by Davidsv** [comment]
Thanks. In my case, I'll have to account for this. I understand it's just the way table storage works though.
